name: CVE-2022-1529-thunderbird

on:
  push:
    branches: 
      - main
    paths:
      - 'containers/cve-2022-1529-thunderbird/**'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_TAG: cve-2022-1529-thunderbird:1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image to be scanned
        run: |
          docker buildx build -f ${{ env.IMAGE_TAG }}/Dockerfile --platform linux/amd64 --tag ${{ env.IMAGE_TAG }} .

      - name: Scan container image with Tenable Cloud Security
        uses: ermetic/actions/container-image/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://us.app.ermetic.com
          name: ${{ env.IMAGE_TAG }}
          fail-on-min-severity: critical
