on:
  push:
    branches: 
      - main
    paths:
      - 'containers/CVE-2021-44228-log4shell/**'

permissions:
  contents: read

env:
  IMAGE_TAG: CVE-2021-44228-log4shell:1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image to be scanned
        run: |
          docker build -t $IMAGE_TAG

      - name: Scan container image with Tenable Cloud Security
        uses: ermetic/actions/container-image/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://us.app.ermetic.com
          name: $IMAGE_TAG
          fail-on-min-severity: critical